version: 2
snapshot:
  widths:
    - 375  # Mobile
    - 768  # Tablet
    - 1280 # Desktop
  minHeight: 1024
  percyCSS: |
    /* Hide elements that may cause flakiness in snapshots */
    .date-time, .timestamp, [data-testid="timestamp"] {
      visibility: hidden !important;
    }

    /* Hide animations and transitions */
    * {
      animation-duration: 0s !important;
      transition-duration: 0s !important;
    }
discovery:
  allowedHostnames:
    - localhost
  disallowedHostnames: []
  networkIdleTimeout: 100
upload:
  files: "./tests/visual/**/*.spec.ts"
  ignore: ""
  stripExtensions: false
