version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - AUTH_SECRET=development-auth-secret
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - NEXT_RUNTIME=nodejs
    depends_on:
      - redis
    # Add hostname aliases for multitenancy testing
    extra_hosts:
      - "fishinggearreviews.com:127.0.0.1"
      - "hikinggearreviews.com:127.0.0.1"
      - "fishing-gear.mydirectory.com:127.0.0.1"
      - "hiking-gear.mydirectory.com:127.0.0.1"
      - "mydirectory.com:127.0.0.1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis-data: