version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: directorymonster-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped
