@echo off
echo Running PermissionGuard tests with minimal output...
npx jest src/components/admin/auth/guards/__tests__/PermissionGuard.test.tsx --silent --no-watchman --colors --reporters=default --json --outputFile=jest-results.json
