version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.all-in-one
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ../circuits:/app/circuits
      - ../crypto-checksums.json:/app/crypto-checksums.json
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
