name: ZKP Authentication System

on:
  push:
    branches: [ main, feature/*, develop ]
    paths:
      - 'circuits/**'
      - 'scripts/zkp-setup.ts'
      - 'scripts/update-zkp-implementation.js'
      - 'src/lib/zkp/**'
      - 'tests/crypto/**'
      - 'tests/lib/zkp-bcrypt.test.ts'
      - 'tests/lib/zkp-mock-adapter-bcrypt.test.ts'
      - 'tests/lib/rate-limit.test.ts'
      - 'tests/types/snarkjs.test.ts'
      - 'src/lib/file-integrity.ts'
      - 'src/lib/rate-limit.ts'
      - 'scripts/generate-checksums.ts'
      - 'scripts/verify-checksums.ts'
      - '.github/workflows/zkp-auth.yml'
      - 'docker-compose.zkp.yml'
      - 'Dockerfile.zkp'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'circuits/**'
      - 'scripts/zkp-setup.ts'
      - 'scripts/update-zkp-implementation.js'
      - 'src/lib/zkp/**'
      - 'tests/crypto/**'
      - 'tests/lib/zkp-bcrypt.test.ts'
      - 'tests/lib/zkp-mock-adapter-bcrypt.test.ts'
      - 'tests/lib/rate-limit.test.ts'
      - 'tests/types/snarkjs.test.ts'
      - 'src/lib/file-integrity.ts'
      - 'src/lib/rate-limit.ts'
      - 'scripts/generate-checksums.ts'
      - 'scripts/verify-checksums.ts'
      - '.github/workflows/zkp-auth.yml'
      - 'docker-compose.zkp.yml'
      - 'Dockerfile.zkp'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Set up ZKP authentication system
      run: npm run zkp:setup

    - name: Run secure ZKP tests
      run: npm run test:crypto:secure

    - name: Run simplified ZKP tests
      run: npm run test:crypto:simplified

    - name: Run ZKP security measures tests
      run: npm run test:crypto:security

    - name: Run dynamic salt generation tests
      run: npm run test:crypto:salt

    - name: Run all crypto tests
      run: npm run test:crypto

    - name: Verify ZKP setup
      run: npm run test:crypto:setup

    - name: Run security improvement tests
      run: npm run test:crypto:security

    - name: Verify cryptographic file integrity
      run: npx ts-node scripts/verify-checksums.ts

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: zkp-auth
        path: |
          circuits/zkp_auth/zkp_auth_final.zkey
          circuits/zkp_auth/verification_key.json
          circuits/zkp_auth/verifier.sol
          circuits/zkp_auth/zkp_auth_js/zkp_auth.wasm

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: zkp-auth
        path: circuits/zkp_auth

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.zkp
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/zkp-auth:latest
          ghcr.io/${{ github.repository }}/zkp-auth:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  security-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --production || true

    - name: Run security improvement checks
      run: |
        echo "Checking for bcrypt implementation..."
        grep -q "bcrypt" src/lib/zkp.ts && echo "✅ bcrypt is implemented" || echo "❌ bcrypt is not implemented"

        echo "Checking for private inputs in ZKP circuit..."
        grep -q "signal private input" circuits/zkp_auth/zkp_auth.circom && echo "✅ Private inputs are properly marked" || echo "❌ Private inputs are not properly marked"

        echo "Checking for TypeScript reserved keyword fix..."
        grep -q "createPowersOfTau" src/types/snarkjs.d.ts && echo "✅ TypeScript reserved keyword is fixed" || echo "❌ TypeScript reserved keyword is not fixed"

        echo "Checking for proper HTTP headers implementation..."
        grep -q "headers: new Headers()" src/lib/rate-limit.ts && echo "✅ HTTP headers are properly implemented" || echo "❌ HTTP headers are not properly implemented"

        echo "Checking for division by zero protection..."
        grep -q "!= 0" circuits/circomlib/montgomery.circom && echo "✅ Division by zero protection is implemented" || echo "❌ Division by zero protection is not implemented"

        echo "Checking for file integrity implementation..."
        [ -f "src/lib/file-integrity.ts" ] && echo "✅ File integrity module exists" || echo "❌ File integrity module does not exist"

        echo "Checking for proper Poseidon hash constants..."
        grep -q "POSEIDON_C10" circuits/poseidon_constants.circom && echo "✅ Proper Poseidon hash constants are implemented" || echo "❌ Proper Poseidon hash constants are not implemented"

        echo "Checking for increased Poseidon round parameters..."
        grep -q "nRoundsF = 8" circuits/zkp_auth/zkp_auth.circom && echo "✅ Increased Poseidon round parameters are implemented" || echo "❌ Increased Poseidon round parameters are not implemented"

        echo "Checking for hash truncation fix..."
        ! grep -q "% BigInt(2\*\*64)" scripts/update-zkp-implementation.js && echo "✅ Hash truncation is fixed" || echo "❌ Hash truncation is not fixed"

    - name: Run SAST scan
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  deploy:
    runs-on: ubuntu-latest
    needs: [docker, security-scan]
    if: github.ref == 'refs/heads/main'
    # You need to create this environment in your GitHub repository settings
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Add deployment steps here
        # This is a placeholder for actual deployment steps
        echo "Deployment complete!"
